import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import { SessionProvider } from "next-auth/react"

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "ByteBlogger",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className + " flex flex-col justify-center items-center min-h-screen py-5 px-4"}>
        <Toaster toastOptions={{ position: "top-right" }} />
        <SessionProvider>
          {children}
        </SessionProvider>
      </body>
    </html>
  );
}
